version: "3.9"
services:
  django:
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      - DJANGO_SETTINGS_MODULE=base.settings

  huey:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    command: ["python", "manage.py", "run_huey"]
    environment:
      - DJANGO_SETTINGS_MODULE=base.settings

  nginx:
    image: nginx:1.23-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/usr/share/nginx/html/media
      - ./static:/usr/share/nginx/html/static
      - ./theme/static:/usr/share/nginx/html/static
    depends_on:
      - django
    ports:
      - 8001:80
