# Generated by Django 4.2.9 on 2024-03-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('scientific_name', models.TextField(blank=True, null=True)),
                ('watering_interval', models.IntegerField(blank=True, default=None, null=True)),
                ('fertilisation_interval', models.IntegerField(blank=True, default=None, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snooze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('midnights', models.IntegerField(default=2)),
                ('event_type', models.CharField(choices=[('WATERING', 'watering'), ('FERTILISATION', 'fertilisation')], default='WATERING', max_length=100)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roze.flower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('light_in_lux', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roze.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='flower',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roze.location'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('WATERING', 'watering'), ('FERTILISATION', 'fertilisation')], default='WATERING', max_length=100)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roze.flower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepresentationalPhoto',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roze.photo')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roze.flower')),
            ],
            options={
                'abstract': False,
            },
            bases=('roze.photo',),
        ),
    ]
