# Generated by Django 4.2.9 on 2024-03-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WATERING', 'watering'), ('FERTILISATION', 'fertilisation'), ('REPOTTING', 'repotting')], default='WATERING', max_length=100),
        ),
        migrations.AlterField(
            model_name='snooze',
            name='event_type',
            field=models.CharField(choices=[('WATERING', 'watering'), ('FERTILISATION', 'fertilisation'), ('REPOTTING', 'repotting')], default='WATERING', max_length=100),
        ),
    ]
